### ISSUE TITLE
Add bulk uploads everywhere

### ISSUE THREAD

**Issue by ayshptk** [nftlabs/nftlabs-sdk-ts#107]

**Comment by atbe** [comment]
Before we work on this, list all the methods that need to be updated, and create subtasks for each so we have a good checklist when reviewing the PR.

**Comment by ayshptk** [comment]
- [ ] `bundle.createAndMintBatch`
- [ ] `drop.lazyMintBatch`
- [ ] `nft.mintBatchTo`

**Comment by atbe** [comment]
This has been merged in #121
