### ISSUE TITLE
Unblock dashboard pack page

### ISSUE THREAD

**Issue by adam-maj** [nftlabs/nftlabs-sdk-ts#112]
- [ ] Fix pack supply after pack creation
- [ ] Fix returned IPFS data on open

Issues:
- When you create a pack, it doesn't create the right supply (if I make a pack with 50 rewards from 3 different NFTs (so 150 total), it will end up creating a pack with supply of 75).
- When you open a pack, it returns the IPFS data of a pack instead of the rewards that you earned (its referencing the wrong contract for the IPFS data)

**Comment by adam-maj** [comment]
The fix for task 2 is probably here: https://discord.com/channels/922584461680443402/922627376330973265/923056418821644359

**Comment by atbe** [comment]
merged in #v1.29.5
