### ISSUE TITLE
Unblock dashboard withdraw balance

### ISSUE THREAD

**Issue by adam-maj** [nftlabs/nftlabs-sdk-ts#113]
The `balanceOfToken` function throws an error:

![image](https://user-images.githubusercontent.com/64697628/147129986-fca9d73b-dfaa-4f8d-8cd9-3fd76fc351a9.png)

**Comment by adam-maj** [comment]
This error might be coming from this line: https://github.com/nftlabs/nftlabs-sdk-ts/blob/8ce839528f723f9d687885b3656bd1e8e7cf37ba/src/modules/app.ts#L909

**Comment by adam-maj** [comment]
Here's the blocked code: https://github.com/nftlabs/console/pull/386/files

**Comment by jakeloo** [comment]
fixed in console and 1.29.4

**Comment by jakeloo** [comment]
fixed in console and 1.29.4
