### ISSUE TITLE
Marketplace v2.0

### ISSUE THREAD

**Issue by atbe** [nftlabs/nftlabs-sdk-ts#119]
This ticket tracks the marketplace v2.0 initial module development.

This is not intended to cover the entire feature, just the progress of the module making it into the sdk.

### Methods remaning to implement:

- [x] `buyoutAuction`
- [x] `buyDirectListing`
- [x] `getActiveBids`
- [x] `closeAuctionListing`
- [x] `removeListing` (converted into two separate method, `cancelDirectListing` and `cancelAuctionListing`

**Comment by atbe** [comment]
Some questions I need answered (cc @nkrishang @jakeloo)

1. When a user decides they want to "buyout" an auction, are they required to buy the entire quantity of tokens for sale? E.g. there is `quantity = 10` of a particular 1155 on an auction. If I decide I want to "buyout" the auction (based on the buyout price), am I **required** to buy all 10? Or can I buyout only a subset?
2. What are the sequence of calls we should make when **cancelling** a direct listing, such that no offers are accepted? Can a direct listing be cancelled?
3. Assuming an auction **does not have a winning bid** can the lister cancel the auction and get their asset returned to them?
4. Assuming an auction **does have a winning bid** and the seller is happy with the current winning bid, can they close the auction and accept the current winning bid? If so, what sequence of calls need to be made?
5. When an auction has **ended** and **there is a winning bid**, what are the sequence of tx's needed in order to distribute the payment to the seller **and** distribute the assets to the buyer? Can this be done in a single call, or should each side of the listing (buyer & seller) come to the marketplace to close their side of the deal (and receive their assets)?

I'll keep updating this list with questions as I wrap up the initial implementation on the sdk side.

**Comment by atbe** [comment]
As of right now, our sdk marketplace interface contains a `removeListing` method. 

I think this should be two distinct methods:

1. `removeDirectListing` -> depending on how the closing of a direct mechanism works, this method is more explicit and clearly communicates that you **can't** use this on an auction (because I'm not yet sure if you *can actually remove* an auction)
2. `closeAuction` -> Closes an auction. Still unsure how this will work until questions 2-4 above are answered
3. `cancelAuction` -> This can only be called if an auction *has not yet started* and should completely cancel the listing and return the sellers assets to them.

**Comment by atbe** [comment]
@jakeloo the PR is ready to go, outside of the methods listed at the top of this ticket.

The two things we're waiting for:

1. Krishang to answer some questions about auction closing procedures
2. Setting up subgraph so that we can supply methods like `getActiveBids` and `getActiveOffers`

**Comment by nkrishang** [comment]
> 1. When a user decides they want to "buyout" an auction, are they required to buy the entire quantity of tokens for sale? E.g. there is `quantity = 10` of a particular 1155 on an auction. If I decide I want to "buyout" the auction (based on the buyout price), am I **required** to buy all 10? Or can I buyout only a subset?


For auctions, there's no way to buy a partial amount of tokens put up for auction -- regardless of whether we're discussing a buyout, or a regular bid.

> 2. What are the sequence of calls we should make when **cancelling** a direct listing, such that no offers are accepted? Can a direct listing be cancelled?

We consider a direct listing effectively 'cancelled' when the quantity of tokens listed in the listing is `0`. So, to cancel a direct listing, one must call [`upateLisitng`](https://github.com/nftlabs/nftlabs-protocols/blob/main/contracts/marketplace/Marketplace.sol#L166) with [`_quantityToList`](https://github.com/nftlabs/nftlabs-protocols/blob/main/contracts/marketplace/Marketplace.sol#L168)  set to `0`.

> 3. Assuming an auction **does not have a winning bid** can the lister cancel the auction and get their asset returned to them?

There's a bug in the contract that prevents the auction creator to have their asset returned to them, in the case you've described. I've opened up [an issue](https://github.com/nftlabs/nftlabs-protocols/issues/77) in the contracts repo. Thanks for pointing it out 👍

> 4. Assuming an auction **does have a winning bid** and the seller is happy with the current winning bid, can they close the auction and accept the current winning bid? If so, what sequence of calls need to be made?

No, the auction creator must wait until the auction's closing to close the auction. Bidder's are permitted to outbid the current winning bid until the closing of the auction window.

> 5. When an auction has **ended** and **there is a winning bid**, what are the sequence of tx's needed in order to distribute the payment to the seller **and** distribute the assets to the buyer? Can this be done in a single call, or should each side of the listing (buyer & seller) come to the marketplace to close their side of the deal (and receive their assets)?
> 

The auction needs to be closed (1) once for the winning bidder, which distributes the auctioned items to the bidder (call [`closeAuction`](https://github.com/nftlabs/nftlabs-protocols/blob/main/contracts/marketplace/Marketplace.sol#L311) with the winning bidder's address as `_closeFor`) and (2) once for the auction creator, which distributes the winning bid to the auction creator (call [`closeAuction`](https://github.com/nftlabs/nftlabs-protocols/blob/main/contracts/marketplace/Marketplace.sol#L311) with the auction creator's address as `_closeFor`)

**Comment by atbe** [comment]
@nkrishang thanks for the answers. I still have a problem with [this condition](https://github.com/nftlabs/nftlabs-protocols/blob/v1.18.0/contracts/marketplace/Marketplace.sol#L320).

> There's a bug in the contract that prevents the auction creator to have their asset returned to them, in the case you've described. I've opened up an issue in the contracts repo. Thanks for pointing it out 👍

(Everything below this comment **assumes the listing has no winning bid**)

With the way the condition is checking the end time, the seller can *only* receive their assets **after** the end time. But if someone accidentally creates an auction and wants to pull it, IMO they should be able to so they can preserve their asset.

There's tons of cases where the seller may want to cancel the auction **before the end time**:

1. They misconfigured the listing and would like to cancel + relist (there are things they *can* update with the `updateListing` function, but they can't change the asset they listed, which is 100% possible. For example someone lists token `#1`, but they meant to list `#2`).
2. They decided they don't want to sell the asset anymore, and there are 0 active
3. etc

Imo, the `targetListing.endTime < block.timestamp` portion of the condition on line 320 should be removed.

**Comment by nkrishang** [comment]
@atbe I think the case you describe is for the frontend or SDK to handle, and not the contract.

The [`toCancel`](https://github.com/nftlabs/nftlabs-protocols/blob/main/contracts/marketplace/Marketplace.sol#L319) check is an example where the contract must operate optimistically on the assumption that an auction was created intentionally, and not by mistake. Another example of operating optimistically on an assumption is creating packs in our `Pack` contract. One can create packs by mistake; redeeming the assets that the packs wrap requires the pack creator to open the packs one by one.

```
Otherwise, if someone creates a listing that lasts 24 hours, their asset is locked away for 24 hours with the chance of being bid on which essentially forfeits the asset to the winning bidder (once the listing ends).
```

From the contract's perspective, this behaviour is intended. For the thirdweb dashboard, this means conveying the finality of an auction (that it cannot be canceled after it has started); for the SDK, this means making the call to create an auction explicit (e.g. `marketplace.createAuction(...)`); for thirdweb at large, this means educating the users about the finality of blockchain transactions and smart contract logic.

**Comment by atbe** [comment]
But what exactly is the motivation around restricting cancellations until after the end time? I don't see any reason why a lister can't cancel a listing if there are no bids.

**Comment by nkrishang** [comment]
The main rationale is [here](https://github.com/nftlabs/nftlabs-protocols/blob/main/contracts/marketplace/marketplace.md#main-difference-in-treatment-direct-vs-auction-listings).

For the contract, given an explicit start and end time for the auction, it's acceptable to place a bid at any moment in that time window. This is because the contract does not anticipate any bidding strategy, or take a stance on when bids should be placed.

Here's a thought experiment: an auction window is between 12:00pm and 1:00pm, and the first bid is going to be made at 12:59pm. It's not up to the contract to decide at 12:58pm that most of the auction window is over and no bids have been made _yet_, so it's acceptable to let the creator cancel the auction since no bids will be made at all. We know this isn't true, because the first bid will land a minute later, at 12:59pm. That's why the contract does not permit the auction creator to cancel the auction after it has started and before it has ended.

**Comment by atbe** [comment]
> Here's a thought experiment: an auction window is between 12:00pm and 1:00pm, and the first bid is going to be made at 12:59pm. It's not up to the contract to decide at 12:58pm that most of the auction window is over and no bids have been made yet, so it's acceptable to let the creator cancel the auction since no bids will be made at all. We know this isn't true, because the first bid will land a minute later, at 12:59pm. That's why the contract does not permit the auction creator to cancel the auction after it has started and before it has ended.

This seems like an extreme case. Nonetheless, I digress. If we hear users requesting that they'd like the ability to cancel before the end time, we can deal with it then. Thanks for the feedback.

**Comment by nkrishang** [comment]
Yep 👍 Also with the new architecture we're working towards, we'll be able to let users toggle between the kinds of commitments they want on auctions (i.e. in general, we'll be able to respond to user feedback on things like these much faster, without us having to stick to a single spec of a higher level concept like "Marketplace").

**Comment by atbe** [comment]
Sounds good.

Btw @nkrishang  with this default value https://github.com/nftlabs/nftlabs-protocols/blob/main/contracts/marketplace/Marketplace.sol#L144 someone who creates an auction might have an auction that goes on forever, and in combination with the closing conditions, an auction could end up locking up an asset forever accidentally.

I don't see a max time duration on the auctions, so this seems risky @nkrishang

**Comment by nkrishang** [comment]
Yep, adding a max time duration might turn out to be necessary. However, the concern with adding a 'max time duration' is that it re-introduces the issue of auctions being vulnerable to being sniped by bots via last minute bids.

We aim to prevent this kind of sniping via the time and bid buffer, with the assumption that there's a ceiling to the willingness to bid on an auction. Since a winning bidder must lock up their bid amount in the marketplace, the auction is bound to have this implicit ceiling. So, for now, the prevention of the 'locking up of assets forever' is the job of the time and bid buffers.

Another rationale of depending on this 'ceiling' created by auction buffers is that if there's a bidder willing to pay more for the auction, they should be able to pay more, and the payoff for the auction creator for waiting more is, in the end, a larger payout at auction closing.

Rationales / assumptions may be debated. The main issue with a max time duration is still that auctions can be sniped by bots via last minute bids.

See this section in the [design doc](https://github.com/nftlabs/nftlabs-protocols/blob/main/contracts/marketplace/marketplace.md) -

>Every auction listing obeys two 'buffers' to make it a fair auction:
>
>1. Time buffer: this is measured in seconds (e.g. 15 minutes or 900 seconds). If a winning bid is made within the buffer of the auction closing (e.g. 15 minutes within the auction closing), the auction's closing time is increased by the buffer to prevent buyers from making last minute winning bids, and to give time to other buyers to make a higher bid if they wish to.
>
>2. Bid buffer: this is a percentage (e.g. 5%). A new bid is considered to be a winning bid only if its bid amount is at least the bid buffer (e.g. 5%) greater than the previous winning bid. This prevents buyers from making very slightly higher bids to win the auctioned items.

**Comment by atbe** [comment]
> So, for now, the prevention of the 'locking up of assets forever' is the job of the time and bid buffers.

Not necessarily. The "max auction time" I'm suggesting is independent of the time buffer.

If someone passes in `UInt256Max` to the `startTime` parameter, their asset is essentially locked away forever, regardless of the buffers. Or if they pass `UInt256Max` to the `endTime`, the same situation occurs.

Without a proper way to cancel an auction that was accidentally created with such a `startTime` value, the asset is essentially burned.

I disagree in the idea that frontends (like console) are expected to warn the user in the event of such a provided configuration, because this assumes that the caller is using some frontend that verifies the parameters. Someone could easily call these methods in the SDK, which does not warn of such a value because it assumes you know what you're doing, and will inevitably result in some locked up assets.

I don't think we should enforce a hard limit at the contract level, but somewhere in the stack there should be a configurable "maximum auction duration" that can protect listers from falling into this trap.

**Comment by atbe** [comment]
@jakeloo IMO, the marketplace branch is ready to merge.

I've added convenience methods like `getListing` & `buyoutListing` that dynamically determine the listing type.

I've also completed the fetching of the `asset` field and all tests are passing. We're ready for prime time.
