### ISSUE TITLE
currency module is trying to use signer to "read" data

### ISSUE THREAD

**Issue by jnsdls** [nftlabs/nftlabs-sdk-ts#12]
causes this issue: https://github.com/nftlabs/console/issues/76

**Comment by ayshptk** [comment]
@jnsdls the console calls the `balance()` function, this requires a signer, `this.readOnlyContract` is only used with the `balanceOf` function 🤔 

``` typescript
        tokenModule?.balance(),
```

---

`totalSupply()` also uses `this.readOnlyContract`, `get()` requires `providerOrSigner` but i guess that is correct? 
am I misunderstanding something?

**Comment by jnsdls** [comment]
I guess that makes sense, probably should be calling `balanceOf()` in console / making sure you are logged in when trying to call balance (or handle the failure)

**Comment by jnsdls** [comment]
I'm closing this and instead re-opening the console issue & fixing it there
