### ISSUE TITLE
isRestrictedTransfer for supported module

### ISSUE THREAD

**Issue by jakeloo** [nftlabs/nftlabs-sdk-ts#125]
In some modules we support non-transferable flag through `setRestrictedTransfer(restricted?: boolean)`
we need to add the getter for it `isRestrictedTransfer(): Promise<boolean>` that returns true / false whether the contract is non-transferrable.

**Comment by atbe** [comment]
@ayshptk a lot of our modules have this:

```solidity
    bool public transfersRestricted;
```

Most of the modules have it. Market/Marketplace/Vote/Splits are a few that I know off the top of my head that don't have it.

This should be a quick one and helps unblock console 🚢

**Comment by atbe** [comment]
This is out in the latest release `v1.29.7`, you can access the variable through the `isTransferRestricted(): Promise<boolean>` method

cc: @adam-maj @jakeloo @jnsdls
