### ISSUE TITLE
NFT module ownerOf on non-existent token fatal error

### ISSUE THREAD

**Issue by jnsdls** [nftlabs/nftlabs-sdk-ts#13]
Reproducible case: https://thirdweb.com/rinkeby/0xe5C11E2d5e930b26CF51AB5155bb88B3654C8b2b/nft-collection/0xf27C2a1c44E6F16Fbcc9FBB582d7799057Dc57a6

Investigation so far:
- reported by pratham
- happened after a token was burnt via python sdk
- error in dev console:
![image](https://user-images.githubusercontent.com/8204858/141015950-85880274-e754-4e43-af9f-ebab04e3db2d.png)

Hunch: Something in the SDK is going through a for loop of token ids and barfs based on one of them not existing => fatal error

**Comment by atbe** [comment]
Hmm @jnsdls that url you posted returns 404?

**Comment by jnsdls** [comment]
> Hmm @jnsdls that url you posted returns 404?

updated url

**Comment by atbe** [comment]
Confirmed that calling `ownerOf` on a burned token throws an error with message

```
thirdweb_web3.exceptions.ContractLogicError: execution reverted: ERC721: owner query for nonexistent token
```

Pushing a PR to the typescript library to wrap the call in a try catch and return `null` if the token has been burned (thus signaling that the token has been burned)

**Comment by atbe** [comment]
PR is up #14

**Comment by atbe** [comment]
Can confirm that this fixes the bug https://thirdweb-www-cpd9lf0ti-thirdweb.vercel.app/rinkeby/0xe5C11E2d5e930b26CF51AB5155bb88B3654C8b2b/nft-collection/0xf27C2a1c44E6F16Fbcc9FBB582d7799057Dc57a6
