### ISSUE TITLE
Create `Pack` examples

### ISSUE THREAD

**Issue by atbe** [nftlabs/nftlabs-sdk-ts#134]
Create the following examples on the portal:

- [x] Deploying a pack module
- [x] ~~Creating a pack with 721s~~ The pack module doesn't support creating a pack with 721s (yet) so we'll ignore this one.
- [x] Creating a pack with 1155s
- [x] Opening packs
- [x] ~~Buying packs~~ This example requires usage of a marketplace, so we'll skip this for now.

They should be here https://thirdweb.com/portal/learn/code-examples

**Comment by ayshptk** [comment]
weird i cant see it [here](https://github.com/orgs/nftlabs/projects/3/views/13?filterQuery=-status%3ADone+assignee%3Aayshptk++) lol

**Comment by jakeloo** [comment]
You need to add Projects -> Thirdweb

**Comment by ayshptk** [comment]
Thx

**Comment by atbe** [comment]
@eabdelmoneim the 3 examples that aren't crossed out are done and on their way to the code-examples portal page!

**Comment by atbe** [comment]
@ayshptk still waiting for these docs to hit the https://thirdweb.com/portal/learn/code-examples page, please update us here when you finish that

**Comment by ayshptk** [comment]
on it!

**Comment by ayshptk** [comment]
@eabdelmoneim you can share the snippets listed [here](https://thirdweb.com/portal/learn/code-examples#pack)
