### ISSUE TITLE
Signature based minting sdk

### ISSUE THREAD

**Issue by ayshptk** [nftlabs/nftlabs-sdk-ts#139]
The feature roadmap:

- [ ] Draft the interface and review with team (likely @atbe)
- [ ] Implement all methods (likely @atbe  + @ayshptk)

**Comment by atbe** [comment]
Things to test **using NFT Collections that were deployed before this change**:

- [ ] Minting a single nft
- [ ] Minting a batch of nfts
- [ ] Transferring a single nft
- [ ] Checking the list of nfts displayed in console on the module page (all nfts should be displayed as before the change)
- [ ] The owner is correctly displayed on the console list for each token
- [ ] Burning a token

And probably many more I can't think of, but this is a good start.

**Comment by eabdelmoneim** [comment]
- [ ] Test setting permissions on both contracts
- [ ] List NFT's on marketplace
- [ ] Buy NFT on marketplace
- [ ] unlist NFT's on marketplace
