### ISSUE TITLE
ClaimConditionPhase.setSnapshot should not be async 

### ISSUE THREAD

**Issue by jakeloo** [nftlabs/nftlabs-sdk-ts#146]
https://github.com/nftlabs/nftlabs-sdk-ts/blob/main/src/factories/ClaimConditionPhase.ts#L109

never return promise in claim condition phase, builder pattern. i.e: on the setSnapshot function.
instead, resolve the promise in `buildCondition()`

Some notes:

- [x] Lets deprecate `setSnapshot`
- [x] Create a new synchronous method called `useSnapshot`

**Comment by atbe** [comment]
Some notes:

- [ ] Lets deprecate `setSnapshot`
- [ ] Create a new synchronous method called `useSnapshot`
