### ISSUE TITLE
BundleModule.getOwned() returning incorrect number owned

### ISSUE THREAD

**Issue by eabdelmoneim** [nftlabs/nftlabs-sdk-ts#177]
our customer slip ran into this bug https://discord.com/channels/834227967404146718/915738548848713818/928982738286018680

I confirmed via the contract https://mumbai.polygonscan.com/address/0xaD62C2Ec189bF8301c129d361f8B6b1CEa56F284#readContract

and using the wallet address 0x05526ab44D5c35a313FcCbC5d0C2b209A0eba8C8 we should have returned 13

![Screen Shot 2022-01-07 at 10 32 25 AM](https://user-images.githubusercontent.com/10700302/148575379-788a64e5-c96a-483d-89de-4e539982c2b9.png)

**Comment by jakeloo** [comment]
@ayshptk can you take a look at this issue

**Comment by eabdelmoneim** [comment]
Ran this test code on the smart contract and the answer you get from BundleModule.get() vs getOwned()

import {ThirdwebSDK} from "@3rdweb/sdk";

const RPC_URL = "https://rpc-mumbai.maticvigil.com/";

const run = async () => {
  const sdk = new ThirdwebSDK(RPC_URL, {
    ipfsGatewayUrl: "https://ipfs.io/ipfs/"
  });

  const bd = sdk.getBundleModule("0xaD62C2Ec189bF8301c129d361f8B6b1CEa56F284");

  console.log(await bd.getOwned("0x05526ab44d5c35a313fccbc5d0c2b209a0eba8c8"));

  console.log(await bd.get("0","0x05526ab44d5c35a313fccbc5d0c2b209a0eba8c8"));
  console.log(await bd.get("1","0x05526ab44d5c35a313fccbc5d0c2b209a0eba8c8"));
}

run().then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })

You can see the output is inconsistent:

[
  {
    creator: '0x05526ab44D5c35a313FcCbC5d0C2b209A0eba8C8',
    supply: BigNumber { _hex: '0x64', _isBigNumber: true },
    metadata: {
      name: '60% ABS',
      description: '',
      image: 'https://ipfs.io/ipfs/QmdkoLTrC4PQshk2nPxKJqJqbQE8a3tvHCgEeAndMNJKqX/0',
      external_url: '',
      background_color: '',
      properties: [Object],
      id: '0',
      uri: 'ipfs://QmX7hTiSQi4u9gWnbEQV366k83TWmJqZueFKNQhEVgcKZz/0/'
    },
    ownedByAddress: 0,
    underlyingType: 0
  },
  {
    creator: '0x05526ab44D5c35a313FcCbC5d0C2b209A0eba8C8',
    supply: BigNumber { _hex: '0x0a', _isBigNumber: true },
    metadata: {
      name: '60% PBT',
      description: '',
      image: 'https://ipfs.io/ipfs/QmVoJH1XdjkndviUxzT4Tyhyw2a5cUMqGgUFWNd6oXNrNT/0',
      external_url: '',
      background_color: '',
      properties: [Object],
      id: '1',
      uri: 'ipfs://QmVWUd53v2yKWSeuPfVU56oEWPgmpyUio6V7DNcW3FqHkP/0/'
    },
    ownedByAddress: 0,
    underlyingType: 0
  }
]
{
  creator: '0x05526ab44D5c35a313FcCbC5d0C2b209A0eba8C8',
  supply: BigNumber { _hex: '0x64', _isBigNumber: true },
  metadata: {
    name: '60% ABS',
    description: '',
    image: 'https://ipfs.io/ipfs/QmdkoLTrC4PQshk2nPxKJqJqbQE8a3tvHCgEeAndMNJKqX/0',
    external_url: '',
    background_color: '',
    properties: { '': '' },
    id: '0',
    uri: 'ipfs://QmX7hTiSQi4u9gWnbEQV366k83TWmJqZueFKNQhEVgcKZz/0/'
  },
  ownedByAddress: 13,
  underlyingType: 0
}
{
  creator: '0x05526ab44D5c35a313FcCbC5d0C2b209A0eba8C8',
  supply: BigNumber { _hex: '0x0a', _isBigNumber: true },
  metadata: {
    name: '60% PBT',
    description: '',
    image: 'https://ipfs.io/ipfs/QmVoJH1XdjkndviUxzT4Tyhyw2a5cUMqGgUFWNd6oXNrNT/0',
    external_url: '',
    background_color: '',
    properties: { '': '' },
    id: '1',
    uri: 'ipfs://QmVWUd53v2yKWSeuPfVU56oEWPgmpyUio6V7DNcW3FqHkP/0/'
  },
  ownedByAddress: 1,
  underlyingType: 0
}

**Comment by eabdelmoneim** [comment]
@ayshptk if you have questions you can talk to @atbe he helped me debug this one

**Comment by eabdelmoneim** [comment]
if you see on Bundle.get() calls, the ownedByAddress is 13,1,0 respectively for tokens 0,1,2 whereas in the case of the ownedBy() for that same address the user is returned ownedByAddress:0
