### ISSUE TITLE
Fix ipfsHash wrong type bug on SDK (impacts dashboard)

### ISSUE THREAD

**Issue by adam-maj** [nftlabs/nftlabs-sdk-ts#221]
Based on a bug this user found:
https://discord.com/channels/834227967404146718/878526837150580736/93380486038880671
<img width="705" alt="Screen Shot 2022-01-20 at 3 12 23 PM" src="https://user-images.githubusercontent.com/64697628/150414668-12c88628-d485-4d57-8dce-698d8696727d.png">

This gets thrown on dashboard NFT Collection page
<img width="401" alt="Screen Shot 2022-01-20 at 3 12 47 PM" src="https://user-images.githubusercontent.com/64697628/150414725-9c3a8a82-ae58-4182-ad90-cf67c7461f6e.png">

Which is getting thrown from the SDK here:
https://github.com/nftlabs/nftlabs-sdk-ts/blob/f6902ffdc8a8a1eb6e20514c801adc9241614efc/src/storage/IpfsStorage.ts#L374

**Comment by ayshptk** [comment]
[dashboard url](https://thirdweb.com/rinkeby/0xBfC560713e4F89d32Ab766b26ed6508d1850D515/nft-collection/0x6e2B847158d7428C3E64f41FA91AC4401C3aB392)

**Comment by ayshptk** [comment]
token id is 2

**Comment by indrajitbnikam** [comment]
@ayshptk @adam-maj How much Estimated time I can expect for this to get resolved? Any rough idea?

**Comment by ayshptk** [comment]
fixing it right now!

**Comment by ayshptk** [comment]
this has been released in `1.36.4`
