### ISSUE TITLE
Need to make the biconomy options configurable

### ISSUE THREAD

**Issue by atbe** [nftlabs/nftlabs-sdk-ts#236]
- Make the API URL configurable:
    - https://github.com/nftlabs/nftlabs-sdk-ts/blob/a1bdebcd044616ad6ccf805c076ab1038efd9960/src/core/index.ts#L609
- Make the deadline configurable
    - https://github.com/nftlabs/nftlabs-sdk-ts/blob/a1bdebcd044616ad6ccf805c076ab1038efd9960/src/core/index.ts#L106
- Make the transaction gas price selection configurable
    - Waiting for biconomy to let us know what the new parameter is we need to pass

**Comment by atbe** [comment]
For dedicated relayers, they have a custom URL, we need to make sure we support overriding this.

**Comment by jakeloo** [comment]
1. Sounds good, i think we can re-use transactionRelayerUrl or something? remove the hardcode in the URL.
2. `deadlineSeconds` is already configured in the SDK options.
