### ISSUE TITLE
NFT Royalty Setter

### ISSUE THREAD

**Issue by jakeloo** [nftlabs/nftlabs-sdk-ts#36]
Unify royalty setters on module. ContractURI and contract-level royalty.

```
module.setRoyaltyBps(...)
module.setRoyaltyRecipient(...)
```

**Comment by atbe** [comment]
Here's how setting the royalty BPS should work:

1. Download the currency metadata
2. Modify the metadata and update the new BPS/recipient address
3. Upload the new metadata to IPFS, save the URL
4. Use `multicall` to call both `setContractURI` and `setRoyaltyBps`

**Comment by atbe** [comment]
Royalty updating done in #49 @ayshptk can you do the same for the recipient now?

**Comment by ayshptk** [comment]
this has been implemented in #49
