### ISSUE TITLE
Supports mintBatchTo in Token

### ISSUE THREAD

**Issue by jakeloo** [nftlabs/nftlabs-sdk-ts#43]
Supports mint batching on Token contract using multicall so it's gas efficient.

a) Airdropping tokens to 100 address using `token.mintTo` for-loop = 4.1mil gas (41k single tx * 100)
b) Airdropping tokens to 100 address using `token.mintTo` + `multicall` = 770k gas.

a) https://mumbai.polygonscan.com/tx/0x572084ff4d520c4713b15c71301eb4a67e383ee0fba1c84b64644479e4afe527
b) https://mumbai.polygonscan.com/tx/0xc0f35ef0819da90ab68e87672eeb032180f419d655433eb2a616a60469fae814

**Comment by atbe** [comment]
This has been merged and released in `v1.18.0`
