### ISSUE TITLE
Replacement Transaction Underpriced on Deployment

### ISSUE THREAD

**Issue by jakeloo** [nftlabs/nftlabs-sdk-ts#46]
```
{\"jsonrpc\":\"2.0\",\"id\":90,\"error\":{\"code\":-32000,\"message\":\"replacement transaction underpriced\"}}
```

**Comment by jakeloo** [comment]
this happens  on nonce duplication.
this means that if you send two transactions back to back too quickly.
one solution would be to manually increment the nonce on the second transaction. :)

**Comment by ayshptk** [comment]
this was an error with the tests, has been fixed.
