### ISSUE TITLE
[Planning] Batch Operations Exceeding Limit

### ISSUE THREAD

**Issue by atbe** [nftlabs/nftlabs-sdk-ts#50]
Here's a list of the modules we have with *batch* functions:

- Drop Module
    - [ ] `lazyMintBatch`
- NFT Module
    - [ ] `mintBatch`
- Bundle Module
    - [ ] `createBatch`
    - [ ] `transferBatchFrom`
    - [ ] `burnBatchFrom`
    - [ ] `mintBatch`
- Pack Module
    - [ ] `transferBatchFrom`

We need to test large batches being passed to these functions to find out how they break, and what we need to do to allow them to support up to 10k inputs in one call.

For the **Drop Module**, the `baseUri` pattern is useful to avoid having to pass 10k args to the function call.

**Comment by jakeloo** [comment]
We need to clear up the `baseUri` behavior since it overrides the previous lazy minted nft uris, unless those tokens were minted using `lazyMintBatch`.
I think there's a good usecase for "reveal"-type drop for allowing overrides.

**Comment by jakeloo** [comment]
Things to keep in mind: block gas limit. every chain has a different limit. we need to find a way to get it or catch the error then break down batches
