### ISSUE TITLE
Support more fields in NFT Metadata for minting

### ISSUE THREAD

**Issue by jakeloo** [nftlabs/nftlabs-sdk-ts#61]
`external_url`: optional - string
`animation_url`: optional - string, file, file[]

file[] = bulk files upload. similar to uploading a directory basically.  if it's hard to implement, we can come back to it later. create a backlog ticket to keep track of it.

**rationale**
external_url: "This is the URL that will appear below the asset's image on OpenSea and will allow users to leave OpenSea and view the item on your site."
animation_url: supports mp3, mp4, webm other media file format.

**Comment by ayshptk** [comment]
#69

**Comment by ayshptk** [comment]
This has been implemented and merged in #70
