### ISSUE TITLE
royalty/splits code examples for FlipFam

### ISSUE THREAD

**Issue by eabdelmoneim** [nftlabs/nftlabs-sdk-ts#63]
need help in getting some code snippets together for FlipFam around splits and royalties.  The typescript examples I need:

1. Simple example of how a split royalty can be setup in SDK
2. They want the ability to change the royalty addresses on an existing split

**Comment by atbe** [comment]
@jakeloo @nkrishang what do we do about point 2.? I'm certain it isn't possible with the current implementation of the splits contract.

**Comment by nkrishang** [comment]
Are you talking about the royalty treasury address for a given module? (https://github.com/nftlabs/nftlabs-protocols/blob/main/contracts/ProtocolControl.sol#L24)

I believe they should be able to change the royalty contract address for any given module whenever they want - https://github.com/nftlabs/nftlabs-protocols/blob/main/contracts/ProtocolControl.sol#L87

However, right now we have no function that migrates all royalty funds in the appropriate manner (according to the shares set in the incumbent treasury) from one royalty treasury to another. 

So, _if_ the customer needs all royalty funds sitting in a single treasury after changing the royalty address, each shareholder will have to withdraw from the previous treasury and deposit in the new treasury. This seems like a hassle; I think our dashboard should make it easy enough to track all royalty treasuries that have funds, from a given module - we emit a `TreasuryUpdated` event to keep track of this - https://github.com/nftlabs/nftlabs-protocols/blob/main/contracts/ProtocolControl.sol#L40

**Comment by atbe** [comment]
> Are you talking about the royalty treasury address for a given module? (https://github.com/nftlabs/nftlabs-protocols/blob/main/contracts/ProtocolControl.sol#L24)

No, I'm talking about updating this variable https://github.com/nftlabs/nftlabs-protocols/blob/main/contracts/Royalty.sol#L39

> So, if the customer needs all royalty funds sitting in a single treasury after changing the royalty address, each shareholder will have to withdraw from the previous treasury and deposit in the new treasury. This seems like a hassle; I think our dashboard should make it easy enough to track all royalty treasuries that have funds, from a given module - we emit a TreasuryUpdated event to keep track of this - https://github.com/nftlabs/nftlabs-protocols/blob/main/contracts/ProtocolControl.sol#L40

Yeah, sounds like the approach they'll have to take.

@nkrishang

**Comment by jakeloo** [comment]
@atbe just to clarify, what they wanted is basically just updating treasury address for the module.
https://github.com/nftlabs/nftlabs-sdk-ts/blob/main/src/modules/app.ts#L317

for example, updating from Splits A -> Splits B.

**Comment by joe-pellegrino** [comment]
Is there a split royalty example anywhere?

**Comment by jakeloo** [comment]
https://thirdweb.com/portal/learn/code-examples#deploying-a-splits-module

**Comment by joe-pellegrino** [comment]
Thank you!
