### ISSUE TITLE
Roles with multicall

### ISSUE THREAD

**Issue by jakeloo** [nftlabs/nftlabs-sdk-ts#74]
today our role system is hard to use because you have to do 1 transaction at a time. it's pretty annoying and poor ux. we should do batch roles updates using multicall to improve the ux of it.

in ModuleWithRoles, add:
 public setAllRoleMembers({ [role_name]: [addresses] }) basically mirroring the interfaces of getAllRoleMembers.
internally, we should do:
1) get all role members to find the diffs for each role_names
2) perform all necessary grantRole
3) perform all necessary revokeRole
2 & 3 should be in multicall.

**Comment by ayshptk** [comment]
this was merged through #79
