### ISSUE TITLE
document setting up claim conditions using factory

### ISSUE THREAD

**Issue by eabdelmoneim** [nftlabs/nftlabs-sdk-ts#87]
We are getting questions on how to use the ClaimConditionFactory.  We need to document with an example how to set it up and what parameters are available

**Comment by atbe** [comment]
@ayshptk can you handle getting some examples setup in the https://thirdweb.com/portal/learn/code-examples page please?

**Comment by ayshptk** [comment]
handed over to @nachoiacovino, closing.

**Comment by atbe** [comment]
@ayshptk you should be able to publish to the portal, why not handle that yourself so we can close this out? I still don't see these examples in the portal https://thirdweb.com/portal/learn/code-examples#lazy-mint-an-nft and even though @nachoiacovino can handle it, you can too.

**Comment by ayshptk** [comment]
@atbe nacho had to add other code snippers before merging it, i have already submitted the PR and he said he will take it from here.

**Comment by ayshptk** [comment]
[link to pr](https://github.com/nftlabs/console/pull/411)
