### ISSUE TITLE
Throw clearer errors on `marketplace.list` method

### ISSUE THREAD

**Issue by atbe** [nftlabs/nftlabs-sdk-ts#95]
We need to create script error types for the following errors when calling `list`:

- [x] If the caller does not have the `lister` role, throw an error
- [x] If the caller does not own the token at the specified asset contract address, throw an error
- [x] If the quantity is 0, throw an error
- [x] If the quantity is > the `tokens per buy`, throw an error

As of right now most of these errors just throw a `failed to estimate gas` error which is useless to the caller and makes it impossible to demystify what's throwing the error.

**Comment by atbe** [comment]
Expectations:

1. Create the `market.test.ts` test file
2. Create a test for each of the error cases above
3. Create strict error types for each of the errors listed on the ticket
4. Test that each of the error cases above throw the correct error

**Comment by ayshptk** [comment]
#97
