### ISSUE TITLE
Bulk upload function needs a flag to allow filenames

### ISSUE THREAD

**Issue by ayshptk** [nftlabs/nftlabs-sdk-ts#98]

**Comment by atbe** [comment]
Before we knock this out, lets put together a decent interface instead of trying to make the `uploadBatch` function too bulky.

**Comment by ayshptk** [comment]
copy of the comment @jakeloo posted in #151 

this will get implemented when this issue closes

we want to support glb file format in nft but opensea doesn't show the 3d model viewer unless the file name of the file ended with .glb
i think with this we basically need to pass through the file name or do filename: image.<file extension>

wokring example: https://opensea.io/assets/0x495f947276749ce646f68ac8c248420045cb7b5e/68026898954899202232907264506226281950552784537796670280536837143556272422913 
working example metadata: https://api.opensea.io/api/v1/metadata/0x495f947276749Ce646f68AC8c248420045cb7b5e/0x9665dc402833aaf056b96623d828c32ebf46a19d0000000000002a0000000001

our broken nft:
https://testnets.opensea.io/assets/0x01f5eb4c476582d29f59a4fd3c7e93d5d45d884a/0
https://opensea.io/assets/matic/0xb4117e019f1a83c7a06b8d30f5574f43307d0206/3
our broken metadata: https://ipfs.io/ipfs/bafkreifi4s6a3a625tymfyohzdcpzj2aqwdkpko7a7lwy3zbjmbueohvfi

gltf viewer:
https://gltf-viewer.donmccurdy.com/
